package com.example.utils

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Log
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.db.BillWithItems
import com.example.data.model.BillStatus
import com.example.data.model.TransactionEntity
import com.example.data.model.TransactionType
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfInvoiceGenerator {
    private const val TAG = "PdfInvoiceGenerator"

    // Standard A4 PDF size in points (72 points per inch)
    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842

    private fun getInvoiceDirectory(context: Context): File {
        val dir = File(context.cacheDir, "invoices")
        if (!dir.exists()) {
            dir.mkdirs()
        }
        return dir
    }

    /**
     * Generates a professional PDF invoice from a Bill with line items.
     */
    fun generateBillInvoicePdf(
        context: Context,
        billWithItems: BillWithItems,
        currencySymbol: String
    ): File? {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        val bill = billWithItems.bill
        val items = billWithItems.items

        // Paints
        val primaryPaint = Paint().apply {
            color = Color.rgb(6, 95, 70) // Emerald Dark #065F46
            isAntiAlias = true
        }

        val primaryContainerPaint = Paint().apply {
            color = Color.rgb(236, 253, 245) // Emerald Light #ECFDF5
            isAntiAlias = true
        }

        val titlePaint = Paint().apply {
            color = Color.WHITE
            textSize = 22f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val subtitlePaint = Paint().apply {
            color = Color.rgb(209, 250, 229)
            textSize = 11f
            isAntiAlias = true
        }

        val headerTextPaint = Paint().apply {
            color = Color.rgb(30, 41, 59)
            textSize = 13f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val bodyTextPaint = Paint().apply {
            color = Color.rgb(71, 85, 105)
            textSize = 10f
            isAntiAlias = true
        }

        val boldBodyPaint = Paint().apply {
            color = Color.rgb(15, 23, 42)
            textSize = 10.5f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val linePaint = Paint().apply {
            color = Color.rgb(226, 232, 240)
            strokeWidth = 1f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }

        val tableHeaderBgPaint = Paint().apply {
            color = Color.rgb(241, 245, 249)
            isAntiAlias = true
        }

        val tableRowAltBgPaint = Paint().apply {
            color = Color.rgb(248, 250, 252)
            isAntiAlias = true
        }

        // Top Header Banner
        val headerHeight = 90f
        canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), headerHeight, primaryPaint)

        canvas.drawText("TAX INVOICE", 36f, 42f, titlePaint)
        canvas.drawText("Generated by Personal Accounting App", 36f, 62f, subtitlePaint)

        // Invoice Number & Status on Header Right
        val rightAlignTitlePaint = Paint(titlePaint).apply {
            textAlign = Paint.Align.RIGHT
            textSize = 16f
        }
        val rightAlignSubPaint = Paint(subtitlePaint).apply {
            textAlign = Paint.Align.RIGHT
        }
        canvas.drawText("#${bill.billNumber}", PAGE_WIDTH - 36f, 42f, rightAlignTitlePaint)

        val statusText = when (bill.status) {
            BillStatus.PAID -> "STATUS: PAID"
            BillStatus.PENDING -> "STATUS: PAYMENT PENDING"
            BillStatus.OVERDUE -> "STATUS: OVERDUE"
            BillStatus.DRAFT -> "STATUS: DRAFT"
        }
        canvas.drawText(statusText, PAGE_WIDTH - 36f, 62f, rightAlignSubPaint)

        // Metadata Columns: Sender / Billed From (Left) & Billed To / Due Date (Right)
        var yPos = 120f
        val leftX = 36f
        val rightX = 340f

        canvas.drawText("FROM:", leftX, yPos, headerTextPaint)
        canvas.drawText("BILLED TO:", rightX, yPos, headerTextPaint)

        yPos += 18f
        canvas.drawText(bill.senderName.ifBlank { "My Business / Accounting" }, leftX, yPos, boldBodyPaint)
        canvas.drawText(bill.clientName, rightX, yPos, boldBodyPaint)

        yPos += 15f
        if (bill.senderContact.isNotBlank()) {
            canvas.drawText(bill.senderContact, leftX, yPos, bodyTextPaint)
        }
        if (bill.clientContact.isNotBlank()) {
            canvas.drawText(bill.clientContact, rightX, yPos, bodyTextPaint)
        }

        yPos += 15f
        if (bill.senderAddress.isNotBlank()) {
            canvas.drawText(bill.senderAddress, leftX, yPos, bodyTextPaint)
        }
        if (bill.clientAddress.isNotBlank()) {
            canvas.drawText(bill.clientAddress, rightX, yPos, bodyTextPaint)
        }

        yPos += 20f
        canvas.drawText("Issue Date: ${Formatters.formatFullDate(bill.issueDateMillis)}", leftX, yPos, bodyTextPaint)
        canvas.drawText("Due Date: ${Formatters.formatFullDate(bill.dueDateMillis)}", rightX, yPos, bodyTextPaint)

        // Line Items Table
        yPos += 28f
        val tableTop = yPos
        val tableBottom = tableTop + 24f
        canvas.drawRoundRect(leftX, tableTop, PAGE_WIDTH - 36f, tableBottom, 4f, 4f, tableHeaderBgPaint)

        val col1 = leftX + 10f       // Description
        val col2 = 330f              // Qty
        val col3 = 390f              // Unit Price
        val col4 = PAGE_WIDTH - 46f  // Total (Right aligned)

        val thPaint = Paint(boldBodyPaint).apply { textSize = 9.5f; color = Color.rgb(71, 85, 105) }
        val thRightPaint = Paint(thPaint).apply { textAlign = Paint.Align.RIGHT }

        canvas.drawText("ITEM DESCRIPTION", col1, tableTop + 16f, thPaint)
        canvas.drawText("QTY", col2, tableTop + 16f, thPaint)
        canvas.drawText("UNIT PRICE", col3, tableTop + 16f, thPaint)
        canvas.drawText("TOTAL", col4, tableTop + 16f, thRightPaint)

        yPos = tableBottom + 16f
        val tdRightPaint = Paint(bodyTextPaint).apply { textAlign = Paint.Align.RIGHT }

        items.forEachIndexed { index, item ->
            if (index % 2 == 1) {
                canvas.drawRect(leftX, yPos - 12f, PAGE_WIDTH - 36f, yPos + 10f, tableRowAltBgPaint)
            }
            val qtyStr = if (item.quantity % 1.0 == 0.0) "${item.quantity.toInt()}" else "${item.quantity}"
            canvas.drawText(item.description, col1, yPos, bodyTextPaint)
            canvas.drawText(qtyStr, col2, yPos, bodyTextPaint)
            canvas.drawText("$currencySymbol${Formatters.formatAmount(item.unitPrice)}", col3, yPos, bodyTextPaint)
            canvas.drawText("$currencySymbol${Formatters.formatAmount(item.totalPrice)}", col4, yPos, tdRightPaint)

            canvas.drawLine(leftX, yPos + 12f, PAGE_WIDTH - 36f, yPos + 12f, linePaint)
            yPos += 24f
        }

        // Summary Card Box (Bottom Right)
        yPos += 14f
        val summaryBoxLeft = 320f
        val summaryBoxRight = PAGE_WIDTH - 36f
        val summaryBoxTop = yPos
        val summaryBoxBottom = summaryBoxTop + 115f

        canvas.drawRoundRect(summaryBoxLeft, summaryBoxTop, summaryBoxRight, summaryBoxBottom, 8f, 8f, primaryContainerPaint)
        val summaryBorderPaint = Paint(linePaint).apply { color = Color.rgb(167, 243, 208) }
        canvas.drawRoundRect(summaryBoxLeft, summaryBoxTop, summaryBoxRight, summaryBoxBottom, 8f, 8f, summaryBorderPaint)

        var sY = summaryBoxTop + 22f
        val sLabelX = summaryBoxLeft + 14f
        val sValueX = summaryBoxRight - 14f

        canvas.drawText("Subtotal:", sLabelX, sY, bodyTextPaint)
        canvas.drawText("$currencySymbol${Formatters.formatAmount(bill.subtotal)}", sValueX, sY, tdRightPaint)

        if (bill.taxRate > 0) {
            sY += 18f
            val taxAmt = bill.subtotal * (bill.taxRate / 100.0)
            canvas.drawText("Tax (${bill.taxRate}%):", sLabelX, sY, bodyTextPaint)
            canvas.drawText("+$currencySymbol${Formatters.formatAmount(taxAmt)}", sValueX, sY, tdRightPaint)
        }

        if (bill.discount > 0) {
            sY += 18f
            canvas.drawText("Discount:", sLabelX, sY, bodyTextPaint)
            canvas.drawText("-$currencySymbol${Formatters.formatAmount(bill.discount)}", sValueX, sY, tdRightPaint)
        }

        sY += 22f
        canvas.drawLine(sLabelX, sY - 8f, sValueX, sY - 8f, summaryBorderPaint)

        val grandTotalLabelPaint = Paint(boldBodyPaint).apply { textSize = 13f; color = Color.rgb(6, 95, 70) }
        val grandTotalValPaint = Paint(boldBodyPaint).apply { textSize = 14f; color = Color.rgb(6, 95, 70); textAlign = Paint.Align.RIGHT }
        canvas.drawText("Total Amount:", sLabelX, sY + 6f, grandTotalLabelPaint)
        canvas.drawText("$currencySymbol${Formatters.formatAmount(bill.totalAmount)}", sValueX, sY + 6f, grandTotalValPaint)

        // Notes & Terms on Left
        if (bill.notes.isNotBlank()) {
            canvas.drawText("NOTES / PAYMENT INSTRUCTIONS:", leftX, summaryBoxTop + 18f, headerTextPaint)
            canvas.drawText(bill.notes, leftX, summaryBoxTop + 36f, bodyTextPaint)
        }

        // Footer at bottom of page
        val footerY = PAGE_HEIGHT - 40f
        canvas.drawLine(leftX, footerY - 14f, PAGE_WIDTH - 36f, footerY - 14f, linePaint)

        val footerPaint = Paint(bodyTextPaint).apply { textSize = 9f; color = Color.rgb(148, 163, 184) }
        canvas.drawText("Thank you for your business! This is a computer-generated tax invoice.", leftX, footerY, footerPaint)

        val timeStamp = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date())
        val timePaint = Paint(footerPaint).apply { textAlign = Paint.Align.RIGHT }
        canvas.drawText("Generated on: $timeStamp", PAGE_WIDTH - 36f, footerY, timePaint)

        document.finishPage(page)

        // Save PDF to App Cache directory for clean sharing
        val safeBillNum = bill.billNumber.replace("[^a-zA-Z0-9_-]".toRegex(), "_")
        val fileName = "Invoice_$safeBillNum.pdf"
        val file = File(getInvoiceDirectory(context), fileName)

        return try {
            val outputStream = FileOutputStream(file)
            document.writeTo(outputStream)
            outputStream.close()
            document.close()
            file
        } catch (e: Exception) {
            Log.e(TAG, "Error writing PDF document", e)
            document.close()
            null
        }
    }

    /**
     * Generates a PDF receipt for any transaction in the ledger.
     */
    fun generateTransactionReceiptPdf(
        context: Context,
        transaction: TransactionEntity,
        currencySymbol: String
    ): File? {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        // Header Background
        val headerColor = when (transaction.type) {
            TransactionType.INCOME -> Color.rgb(6, 95, 70) // Emerald
            TransactionType.EXPENSE -> Color.rgb(159, 18, 57) // Rose/Red
            TransactionType.TRANSFER -> Color.rgb(30, 58, 138) // Blue
        }

        val headerPaint = Paint().apply { color = headerColor; isAntiAlias = true }
        val whiteTitlePaint = Paint().apply {
            color = Color.WHITE
            textSize = 20f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }
        val whiteSubPaint = Paint().apply { color = Color.rgb(241, 245, 249); textSize = 11f; isAntiAlias = true }
        val headerHeight = 90f
        canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), headerHeight, headerPaint)

        val receiptTitle = when (transaction.type) {
            TransactionType.INCOME -> "PAYMENT RECEIPT"
            TransactionType.EXPENSE -> "EXPENSE VOUCHER"
            TransactionType.TRANSFER -> "TRANSFER RECEIPT"
        }

        canvas.drawText(receiptTitle, 36f, 42f, whiteTitlePaint)
        canvas.drawText("Personal Accounting Ledger", 36f, 62f, whiteSubPaint)

        val rightAlignWhite = Paint(whiteTitlePaint).apply { textAlign = Paint.Align.RIGHT; textSize = 14f }
        canvas.drawText("TXN #${transaction.id}", PAGE_WIDTH - 36f, 42f, rightAlignWhite)
        val dateText = Formatters.formatFullDate(transaction.dateMillis) + " " + Formatters.formatTime(transaction.dateMillis)
        val rightAlignSub = Paint(whiteSubPaint).apply { textAlign = Paint.Align.RIGHT }
        canvas.drawText(dateText, PAGE_WIDTH - 36f, 62f, rightAlignSub)

        // Amount Box (Hero)
        val amountBoxTop = 110f
        val amountBoxBottom = 190f
        val bgPaint = Paint().apply { color = Color.rgb(248, 250, 252); isAntiAlias = true }
        val borderPaint = Paint().apply {
            color = Color.rgb(226, 232, 240)
            style = Paint.Style.STROKE
            strokeWidth = 1.5f
            isAntiAlias = true
        }

        canvas.drawRoundRect(36f, amountBoxTop, PAGE_WIDTH - 36f, amountBoxBottom, 12f, 12f, bgPaint)
        canvas.drawRoundRect(36f, amountBoxTop, PAGE_WIDTH - 36f, amountBoxBottom, 12f, 12f, borderPaint)

        val amtLabelPaint = Paint().apply { color = Color.rgb(100, 116, 139); textSize = 11f; isAntiAlias = true }
        val amtValPaint = Paint().apply {
            color = headerColor
            textSize = 26f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        canvas.drawText("TRANSACTION AMOUNT", 56f, amountBoxTop + 32f, amtLabelPaint)
        val sign = when (transaction.type) {
            TransactionType.INCOME -> "+"
            TransactionType.EXPENSE -> "-"
            TransactionType.TRANSFER -> "⇄ "
        }
        canvas.drawText("$sign$currencySymbol${Formatters.formatAmount(transaction.amount)}", 56f, amountBoxTop + 65f, amtValPaint)

        // Key-Value Details Grid
        var y = 220f
        val rowHeight = 36f
        val linePaint = Paint().apply { color = Color.rgb(241, 245, 249); strokeWidth = 1f; isAntiAlias = true }
        val keyPaint = Paint().apply { color = Color.rgb(100, 116, 139); textSize = 11f; isAntiAlias = true }
        val valPaint = Paint().apply {
            color = Color.rgb(15, 23, 42)
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val rows = listOf(
            "Transaction Type" to transaction.type.name,
            "Category" to transaction.category,
            "Account / Wallet" to transaction.accountName,
            "Description / Note" to if (transaction.note.isNotBlank()) transaction.note else "—",
            "Linked Invoice" to if (transaction.billId != null) "Invoice #${transaction.billId}" else "None",
            "Verification Status" to "Recorded & Verified in Local Ledger"
        )

        rows.forEach { (key, value) ->
            canvas.drawText(key, 56f, y + 16f, keyPaint)
            canvas.drawText(value, 240f, y + 16f, valPaint)
            canvas.drawLine(36f, y + 26f, PAGE_WIDTH - 36f, y + 26f, linePaint)
            y += rowHeight
        }

        // Footer
        val footerY = PAGE_HEIGHT - 40f
        val footerPaint = Paint().apply { color = Color.rgb(148, 163, 184); textSize = 9f; isAntiAlias = true }
        canvas.drawText("Official transaction voucher generated by Personal Accounting.", 36f, footerY, footerPaint)

        document.finishPage(page)

        val fileName = "Receipt_TXN_${transaction.id}.pdf"
        val file = File(getInvoiceDirectory(context), fileName)

        return try {
            val outputStream = FileOutputStream(file)
            document.writeTo(outputStream)
            outputStream.close()
            document.close()
            file
        } catch (e: Exception) {
            Log.e(TAG, "Error writing PDF receipt", e)
            document.close()
            null
        }
    }

    /**
     * Triggers the Android system share sheet for the generated PDF.
     */
    fun sharePdf(context: Context, file: File, chooserTitle: String = "Share Invoice PDF") {
        try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, file.nameWithoutExtension)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(shareIntent, chooserTitle).apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(chooser)
        } catch (e: Exception) {
            Log.e(TAG, "Error sharing PDF", e)
            Toast.makeText(context, "Could not open share menu: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    /**
     * Opens the PDF in a viewer app.
     */
    fun viewPdf(context: Context, file: File) {
        try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val viewIntent = Intent(Intent.ACTION_VIEW).apply {
                setDataAndType(uri, "application/pdf")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }

            context.startActivity(viewIntent)
        } catch (e: Exception) {
            Log.e(TAG, "Error viewing PDF", e)
            Toast.makeText(context, "No PDF viewer found on device. Use Share to export.", Toast.LENGTH_SHORT).show()
        }
    }

    /**
     * Saves the PDF into public Downloads or external storage.
     */
    fun savePdfToDownloads(context: Context, sourceFile: File, displayName: String): Boolean {
        return try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                val contentValues = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, "$displayName.pdf")
                    put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                    put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/AccountingInvoices")
                }

                val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    val outputStream: OutputStream? = context.contentResolver.openOutputStream(uri)
                    outputStream?.use { out ->
                        sourceFile.inputStream().use { input ->
                            input.copyTo(out)
                        }
                    }
                    Toast.makeText(context, "Saved to Downloads/AccountingInvoices!", Toast.LENGTH_LONG).show()
                    true
                } else {
                    false
                }
            } else {
                val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                val targetFile = File(downloadsDir, "$displayName.pdf")
                sourceFile.copyTo(targetFile, overwrite = true)
                Toast.makeText(context, "Saved to Downloads: ${targetFile.name}", Toast.LENGTH_LONG).show()
                true
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error saving to Downloads", e)
            Toast.makeText(context, "Saved internally: ${sourceFile.name}", Toast.LENGTH_SHORT).show()
            false
        }
    }
}
